### ISSUE TITLE
Can't install print-env

### ISSUE THREAD

**Issue by ledroide** [pedrobarco/kubectl-env#9] opened 2022-05-03 08:06 UTC
Description : None of installation methods works.
```bash
$ kubectl krew install print-env
W0503 09:57:40.128543  540619 install.go:164] failed to install plugin "print-env": install failed: failed to unpack into staging dir: failed to unpack the plugin archive: checksum does not match, want: 247c0329fa51ac84a039113fbb884432568da03d06b767e906371b0b585d3523, got 64695649afbf64c06aed226a4a101e1d9fa8149f3857c8563980e6e3377c20bd
failed to install some plugins: [print-env]: install failed: failed to unpack into staging dir: failed to unpack the plugin archive: checksum does not match, want: 247c0329fa51ac84a039113fbb884432568da03d06b767e906371b0b585d3523, got 64695649afbf64c06aed226a4a101e1d9fa8149f3857c8563980e6e3377c20bd
```
```bash
$ go install github.com/pedrobarco/kubectl-print-env
go: 'go install' requires a version when current directory is not in a module
        Try 'go install github.com/pedrobarco/kubectl-print-env@latest' to install the latest version
```
```bash
$ go install github.com/pedrobarco/kubectl-print-env@latest
go: downloading github.com/pedrobarco/kubectl-print-env v0.1.1
go: github.com/pedrobarco/kubectl-print-env@latest: module github.com/pedrobarco/kubectl-print-env@latest found (v0.1.1), but does not contain package github.com/pedrobarco/kubectl-print-env
```
```bash
$ go install github.com/pedrobarco/kubectl-print-env@v0.1.1
go: github.com/pedrobarco/kubectl-print-env@v0.1.1: module github.com/pedrobarco/kubectl-print-env@v0.1.1 found, but does not contain package github.com/pedrobarco/kubectl-print-env
```
```bash
$ go install github.com/pedrobarco/kubectl-print-env@v0.1.0
go: downloading github.com/pedrobarco/kubectl-print-env v0.1.0
go: github.com/pedrobarco/kubectl-print-env@v0.1.0: module github.com/pedrobarco/kubectl-print-env@v0.1.0 found, but does not contain package github.com/pedrobarco/kubectl-print-env
```
```bash
$ make build
fatal: No annotated tags can describe '850f2de510a8973556882823287d88953f5f4e2a'.
However, there were unannotated tags: try --tags.
(...)
```

**Comment by pedrobarco** [comment] 2022-06-08 14:12
Jeez, my bad there... I'm so sorry for the late response. I'll take a look into it today. 
Hopefully I'll get this working by the end of the week.

**Comment by dbirks** [comment] 2022-06-08 14:22
Oh hey you were looking at it the same time as me. I'm wondering if it just needs a new release. I ran this locally, and get what looks like the right hash:

```
docker run -v $PWD/.krew.yaml:/tmp/template-file.yaml rajatjindal/krew-release-bot:v0.0.43 krew-release-bot template --tag v0.1.1 --template-file /tmp/template-file.yaml
```
Outputs:
```
...
  - bin: kubectl-print-env
    uri: https://github.com/pedrobarco/kubectl-print-env/releases/download/v0.1.1/kubectl-print-env_v0.1.1_linux_amd64.tar.gz
    sha256: 64695649afbf64c06aed226a4a101e1d9fa8149f3857c8563980e6e3377c20bd
    selector:
      matchLabels:
        os: linux
        arch: amd64
...
```

**Comment by pedrobarco** [comment] 2022-06-08 14:25
I don't remember what was going on with my CD but [it failed](https://github.com/pedrobarco/kubectl-print-env/runs/6047960444?check_suite_focus=true) when releasing the "broken" one.
I might just force a new one, just to make sure it works via `krew`.

**Comment by pedrobarco** [comment] 2022-06-08 14:38
Here is the run: [runs/6795657599](https://github.com/pedrobarco/kubectl-print-env/runs/6795657599). If it doesn't work then I'll have to look into it later.
In the meantime, if you really need to used the plugin:
* checkout the [releases ](https://github.com/pedrobarco/kubectl-print-env/releases) page
*  `make build` will work, even if it prints those error messages (that message is a git message saying that it couldn't parse the current tag, nothing to worry about)

**Comment by pedrobarco** [comment] 2022-06-08 14:40
~~The run still failed in the CD stage, I'll dig into this tonight.~~ 
Looks like it's working now ⛵

**Comment by dbirks** [comment] 2022-06-08 14:54
I think that view was linking the old failed action because they shared the same commit, but looks like it ran nicely:

![image](https://user-images.githubusercontent.com/7545665/172647774-2cc061a5-e875-4cec-a6ca-940b2fec0f35.png)

And the PR to krew-index was auto-merged:
https://github.com/kubernetes-sigs/krew-index/pull/2331

And I can confirm I can install locally! :tada: 
Thanks! This plugin looks quite nice

**Comment by pedrobarco** [comment] 2022-06-08 15:01
Oh, you're right! My bad 😄. Thanks! 
Nevertheless, I'll not close this issue until I have the remaining installation methods working.

Feel free to create as much issues you want: either bugs or feature requests. Better yet, just fork it and submit a PR.

**Comment by dbirks** [comment] 2022-06-08 15:12
(Oh my "install locally" phrase probably made it sound like I was using the Makefile. Just wanted to confirm I can install with `kubectl krew install print-env` like normal. Thanks again for the release :tada: )

**Closed as completed** 2022-06-11 19:07 UTC
Labels: bug, documentation
